### ISSUE TITLE
ctrl+c does not work in zsh

### ISSUE THREAD

**Issue by johan-bjareholt** [Otto-AA/aw-watcher-bash#3]
It sometimes works though, kind of odd

Working example:
 - Open htop
 - ctrl+c
 - exits successfully

Broken example:
 - Enters 'ls' without executing
 - ctrl+c to clear the row
 - nothing happens?

When i comment out the trap line it works fine

    trap aw-watcher-terminal-preclose INT TERM EXIT

**Comment by Otto-AA** [comment]
I guess this gets resolved when using `trap 'aw-watcher-terminal-preclose' TERM EXIT` instead?

Honestly I don't know why I've put `INT` there and actually removed it in my .zshrc file. (But apparently forgot to update the README.md... Putting it into a file, as you suggested should help to not forget these things :smile: )

**Comment by johan-bjareholt** [comment]
Works, closing :)
