### ISSUE TITLE
Merge aw-watcher-bash.sh and aw-watcher-bash-preexec.sh

### ISSUE THREAD

**Issue by Otto-AA** [Otto-AA/aw-watcher-bash#5]
As mentioned [here](https://github.com/Otto-AA/aw-watcher-bash/pull/4#issue-199800086) it would be nice for the install process to merge aw-watcher-bash.sh and aw-watcher-bash-preexec.sh

The problem I face with this is, that the code of aw-watcher-bash.sh partly depends on being executed by bash. Therefore, if we merge it and then put it (for instance) into .zshrc, it will break when it gets executed by zsh. In particular arrays are treated differently in these two shells (bash has them zero-indexed, zsh one-indexed).

Do you have an idea, how we could fix this, @johan-bjareholt ?

If not, I would keep these files separated.

**Comment by johan-bjareholt** [comment]
> The problem I face with this is, that the code of aw-watcher-bash.sh partly depends on being executed by bash. Therefore, if we merge it and then put it (for instance) into .zshrc, it will break when it gets executed by zsh. In particular arrays are treated differently in these two shells (bash has them zero-indexed, zsh one-indexed).

In the code we don't need to specify specific indexes but only append to the array, so this issue seems to be fine.
